unstable_features = true

max_width = 100

use_field_init_shorthand = true

group_imports = "StdExternalCrate"

imports_granularity = "Crate"

where_single_line = false

remove_nested_parens = true

format_code_in_doc_comments = true
wrap_comments = true

reorder_impl_items = true
reorder_modules = true